---
toolbx_packages_general_packages:
  - ansible
  - ansible-collection-ansible-posix
  - ansible-collection-community-general
  - ansible-collection-containers-podman
  - ansible-lint
  - bat  # Like cat, but cooler
  - below
  # - binwalk  # Broken on F43
  - git
  - htop
  - hugo
  - hyfetch
  - just
  - nyancat
  # - ollama  # too large
  - opentofu
  - optipng
  # - pandoc  # too large
  - pre-commit
  - python3-passlib
  - rpmreaper
  - yt-dlp
...
