---
toolbx_packages_general_packages:
  - ansible
  - ansible-collection-ansible-posix
  - ansible-collection-community-general
  - ansible-collection-containers-podman
  - ansible-lint
  - bat  # Like cat, but cooler
  - below
  - binwalk
  - git
  - htop
  - hugo
  - hyfetch
  - nyancat
  - ollama
  - opentofu
  - optipng
  - pandoc
  - pre-commit
  - python3-passlib
  - rpmreaper
  - texlive-scheme-full  # This is huge but it's the lazy way to ensure all Pandoc features work
  - yt-dlp
...
